name: FSSE PR Checker

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      ## Flutter Part
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.5'

      - name: Check Flutter
        run: flutter build apk
